# Generated by Django 3.2 on 2024-10-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanHistori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_jawaban', models.TextField(blank=True, null=True)),
                ('bobot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_histori', to='myapp.instansi')),
                ('jawaban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_histori', to='myapp.jawaban')),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_histori', to='myapp.pertanyaan')),
                ('pertanyaan_instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_histori', to='myapp.pertanyaaninstansi')),
                ('pilihan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_histori', to='myapp.pilihan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_histori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jawaban Histori',
                'verbose_name_plural': 'Jawaban Histori',
            },
        ),
        migrations.CreateModel(
            name='JawabanFinalHistori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('pending', 'Pending')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_final_histori', to='myapp.instansi')),
                ('jawaban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_final_histori', to='myapp.jawaban')),
                ('jawaban_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_final_histori', to='myapp.jawabanfinal')),
                ('pilihan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jawaban_final_histori', to='myapp.pilihan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jawaban_final_histori', to=settings.AUTH_USER_MODEL)),
                ('verifikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifikator_jawaban_final_histori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jawaban Final Histori',
                'verbose_name_plural': 'Jawaban Final Histori',
            },
        ),
    ]
