# Generated by Django 3.2 on 2024-10-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jawabanfinalhistori_jawabanhistori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filejawaban',
            name='content_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filepertanyaan',
            name='content_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filepertanyaaninstansi',
            name='content_type',
            field=models.TextField(),
        ),
    ]
