# Generated by Django 3.2 on 2024-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20241031_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('verifikator', 'Verifikator'), ('operator', 'Operator')], default='user', max_length=20),
        ),
    ]
